/* Automatically generated by './build/bin/build-entry.js' */

import Bus from './common.js';
import question from './question.vue';


//
// const components = [
//   demo
// ];
//
// const install = function(Vue, opts = {}) {
//
//   components.map(component => {
//     Vue.component(component.name, component);
//   });
// };
//
// /* istanbul ignore if */
// if (typeof window !== 'undefined' && window.Vue) {
//   install(window.Vue);
// }

export default question;
export{Bus}

