export default {
  "mheader":{
    "card_type":"mheader",
    'submenu':[
      {
        title:'caoke的个人博客',
        name:'index',

      },
      {
        title:'marvel组件',
        name:'marvel',
        submenu:[
          {
            title:'gongsi',
            name:'gongsi',
          }
        ]
      },
      {
        title:'源码下载',
        name:'page2',
      }
    ]
  },
  "footer":{
    "card_type":"footer"
  },
  routes: [
    {
      path: '/',
      name: 'index',
      card_group:[],
    },
    {
      path: '/marvel',
      name: 'marvel',
      card_group:[],
    },
    {
      path: '/marvel/:pname/:cname',
      name: 'marvelItem',
      leftMenu:{
        "card_type":"menu1",
        'submenu':[
          {
            title:'',
            url:'',
            card_group:[],
            submenu:[
              {
                title:'',
                url:'',
                card_group:[]
              }
            ],
          },
          {
            title:'',
            url:'',
            card_group:[],
            submenu:[
              {
                title:'',
                url:'',
                card_group:[]
              }
            ],
          }
        ]
      },
      card_group:[],
    },
    {
      path: '/page2',
      name: 'page2',
      card_group:[],
    }
  ],
  data:{
    'index':{
      card_group:[]
    },
    'page1':{
      leftMenu:{
        "card_type":"menu1",
        'el-menu':[
          {
            title:'',
            url:'',
            card_group:[],
            submenu:[
              {
                title:'',
                url:'',
                card_group:[]
              }
            ],
          },
          {
            title:'',
            url:'',
            card_group:[],
            submenu:[
              {
                title:'',
                url:'',
                card_group:[]
              }
            ],
          }
        ]
      },
      card_group:[]
    },
    'page2':{
      card_group:[]
    }
  }
}
